# Generated by Django 2.0.1 on 2018-03-12 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('avatar_url', models.CharField(blank=True, max_length=256, null=True)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='dob')),
                ('public_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='public_token')),
                ('access_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='access_token')),
                ('item_ID', models.CharField(blank=True, max_length=100, null=True, verbose_name='item_ID')),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
