# Generated by Django 2.0.1 on 2018-04-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180312_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='just_signed_up',
            field=models.BooleanField(default=True),
        ),
    ]
