# Generated by Django 2.0.1 on 2018-03-28 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('access_token', models.CharField(blank=True, default='', max_length=100)),
                ('item_id', models.CharField(blank=True, default='', max_length=100)),
                ('request_id', models.CharField(blank=True, default='', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('item_id',),
            },
        ),
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('public_token', models.CharField(blank=True, default='', max_length=100)),
                ('request_id', models.CharField(blank=True, default='', max_length=25)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('public_token',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('accounts', models.CharField(blank=True, default='', max_length=100)),
                ('transactions', models.CharField(blank=True, default='', max_length=100)),
                ('account_id', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.CharField(blank=True, default='', max_length=100)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('category_id', models.CharField(blank=True, default='', max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('lat', models.CharField(blank=True, default='', max_length=100)),
                ('lon', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('payment_meta', models.CharField(blank=True, default='', max_length=100)),
                ('pending', models.CharField(blank=True, default='', max_length=100)),
                ('pending_transaction_id', models.CharField(blank=True, default='', max_length=100)),
                ('account_owner', models.CharField(blank=True, default='', max_length=100)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=100)),
                ('transaction_type', models.CharField(blank=True, default='', max_length=100)),
                ('item', models.CharField(blank=True, default='', max_length=100)),
                ('total_transactions', models.CharField(blank=True, default='', max_length=100)),
                ('request_id', models.CharField(blank=True, default='', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('accounts',),
            },
        ),
    ]
