# Generated by Django 2.0.1 on 2018-04-21 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transplaid', '0003_auto_20180405_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transplaid.Transaction')),
            ],
            options={
                'db_table': 'daily_transaction',
            },
            bases=('transplaid.transaction',),
        ),
    ]
