# Generated by Django 2.0.1 on 2018-04-30 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transplaid', '0004_dailytransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialPullTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('account_id', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.CharField(blank=True, default='', max_length=100)),
                ('category', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('category_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('lat', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('lon', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('pending', models.CharField(blank=True, default='', max_length=100)),
                ('pending_transaction_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('account_owner', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=100)),
                ('transaction_type', models.CharField(blank=True, default='', max_length=100)),
                ('item', models.CharField(blank=True, default='', max_length=100)),
                ('request_id', models.CharField(blank=True, default='', max_length=100)),
                ('payment_method', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('by_order_of', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('payee', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('ppd_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('reference_number', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('payment_processor', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('date', models.DateField()),
                ('zip', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('store_number', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial_pull', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'initial_pull',
            },
        ),
    ]
